name: CI

on:
  pull_request:
    branches: ['master']
    paths: ['cls/**/*.cls']
  push:
    branches: ['master']

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Clone this repository
      uses: actions/checkout@v2
      with:
        path: app
    - name: Run tests
      run: |
        docker pull rfns/iris-ci:0.5.2
        docker run -t --rm --name ci -v $PWD/app:/opt/ci/app -e TEST_SUITE=cls/UnitTest rfns/iris-ci:0.5.2

